import {TestBed} from '@angular/core/testing';
import {provideHttpClient,withXhr} from '@angular/common/http';
import {provideHttpClientTesting,HttpTestingController} from '@angular/common/http/testing';
import {describe,it,expect,vi} from 'vitest';
import {AppModule} from '../../app.module';
import {AuthService} from '../../services/security/auth.service';
import {StaffSettingsComponent} from './staff-settings.component';

describe('Staff settings and authenticator enrollment',()=>{
  it('saves grouped alert choices and quiet hours without enabling delivery',async()=>{
    await TestBed.configureTestingModule({imports:[AppModule],providers:[provideHttpClient(withXhr()),provideHttpClientTesting(),{provide:AuthService,useValue:{isStaff:true,isAdmin:true,accountLabel:'staff@example.test',roleLabel:'Administration'}}]}).compileComponents();
    const fixture=TestBed.createComponent(StaffSettingsComponent),c=fixture.componentInstance,http=TestBed.inject(HttpTestingController);
    const topics=[{id:'backupFailed',group:'Operations & recovery',label:'Backup failed',description:'A backup needs attention.'}];
    fixture.detectChanges();
    http.expectOne('/api/cubit/staff/preferences').flush({email:'staff@example.test',topics,preferences:{enabled:false,unknownFobs:false,refusedFobs:false,dedupeMinutes:15,revision:1}});
    http.expectOne('/api/account/notices').flush({rows:[]});
    http.expectOne('/api/account').flush({email:'staff@example.test',mfaEnabled:false,mfaAvailable:true,sharedDemo:false,passwordResetEmailAvailable:false});
    await fixture.whenStable();fixture.detectChanges();
    expect(c.topicGroups).toEqual(['Operations & recovery']);
    const p=c.preferences!;p.enabled=true;p.topics['backupFailed']=true;p.delivery={quietHours:true,start:'22:00',end:'08:00',timezone:'America/New_York'};
    expect(c.selectedCount('Operations & recovery')).toBe(1);
    c.previewAlerts();http.expectNone('/api/cubit/staff/preferences/preview');
    p.delivery.timezone='Invalid/Zone';c.save();http.expectNone('/api/cubit/staff/preferences');
    p.delivery.timezone='America/New_York';c.save();
    const saving=http.expectOne('/api/cubit/staff/preferences');expect(saving.request.body.topics.backupFailed).toBe(true);expect(saving.request.body.delivery.quietHours).toBe(true);
    saving.flush({email:'staff@example.test',topics,preferences:{...p,revision:2},deliveryEnabled:false});
    expect(c.preferencesDirty()).toBe(false);expect(c.message).toContain('delivery remains off');
    c.previewAlerts();http.expectOne('/api/cubit/staff/preferences/preview').flush({results:[],examples:[{topic:'Backup failed',group:'Operations & recovery',decision:'Quiet hours: defer'}]});
    expect(c.topicPreview[0].decision).toContain('Quiet hours');http.verify();fixture.destroy();
  });
  it('keeps recovery codes visible and blocks other requests after MFA revokes the session',async()=>{
    await TestBed.configureTestingModule({imports:[AppModule],providers:[provideHttpClient(withXhr()),provideHttpClientTesting(),{provide:AuthService,useValue:{isStaff:true,isAdmin:true,accountLabel:'staff@example.test',roleLabel:'Administration',logout:vi.fn()}}]}).compileComponents();
    const fixture=TestBed.createComponent(StaffSettingsComponent),c=fixture.componentInstance,http=TestBed.inject(HttpTestingController);
    fixture.detectChanges();
    http.expectOne('/api/cubit/staff/preferences').flush({email:'staff@example.test',preferences:{enabled:false,unknownFobs:true,refusedFobs:true,dedupeMinutes:15,revision:1}});
    http.expectOne('/api/account/notices').flush({rows:[]});
    http.expectOne('/api/account').flush({mfaEnabled:false,mfaAvailable:true,sharedDemo:false});
    await fixture.whenStable();fixture.detectChanges();
    c.preferences!.enabled=true;fixture.detectChanges();
    c.security!.password='fictional-passphrase';await c.security!.startMfa();http.expectNone('/api/account/mfa/start');
    c.cancelPreferences();fixture.detectChanges();expect(c.hasUnsavedChanges()).toBe(false);
    c.security!.code='123456';const confirming=c.security!.confirmMfa();http.expectOne('/api/account/mfa/confirm').flush({recoveryCodes:['fictional-recovery-code']});await confirming;fixture.detectChanges();
    expect(c.hasUnsavedChanges()).toBe(true);expect(c.protectingCodes).toBe(true);
    expect(fixture.nativeElement.textContent).toContain('fictional-recovery-code');
    c.previewAlerts();c.acknowledge('notice');c.load();c.loadNotices();http.verify();
    expect(TestBed.inject(AuthService).logout).not.toHaveBeenCalled();
    c.security!.finishSetup();expect(TestBed.inject(AuthService).logout).toHaveBeenCalled();expect(c.hasUnsavedChanges()).toBe(false);
    fixture.destroy();
  });
});
