import { HealthTrendComponent } from './health-trend.component';
import { OrgDatePipe } from '../../services/org-date.pipe';
import {Component,OnInit,OnDestroy,Output,EventEmitter,ChangeDetectionStrategy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {HttpClient} from '@angular/common/http';
import {Subscription} from 'rxjs';
@Component({selector:'app-system-health',standalone:true,imports:[HealthTrendComponent,OrgDatePipe,CommonModule],changeDetection:ChangeDetectionStrategy.Eager,
styles:[`:host{display:block}.health-history-controls{display:flex;align-items:center;gap:18px;flex-wrap:wrap;margin:16px 0}.health-history-controls label{display:flex;gap:8px;align-items:center}.health-history-controls small{color:#526780}.health-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.health-check{border:1px solid var(--line);border-radius:8px;padding:16px}.health-check header{display:flex;justify-content:space-between;gap:12px;align-items:start}.health-check p{margin:8px 0 0;font-size:13px;overflow-wrap:anywhere}.health-status{font-size:12px;padding:3px 8px;border-radius:5px;background:#edf2f7;white-space:nowrap}.health-status.ok{background:#e9f4eb;color:#245631}.health-status.warning{background:#fff4d5;color:#785514}.health-status.critical{background:#fff0f0;color:#99232b}@media(max-width:700px){.health-checks{grid-template-columns:1fr}}`],
template:`<section class="panel detail-panel" aria-labelledby="system-health-title"><div class="section-heading"><h2 id="system-health-title">System health</h2><button class="secondary" (click)="load()" [disabled]="loading">{{loading?'Checking…':'Refresh status'}}</button></div><p class="muted">{{data?.message||'Read-only checks for storage, database, backups and connectivity.'}}</p>@if(error){<p class="error" role="alert">{{error}}</p>}@if(data){<p class="muted">Checked {{data.checkedAt|orgDate:'medium'}} · Server checks are cached for up to 30 seconds.</p><div class="health-history-controls">@if(!data.demo){<label>History<select [value]="range" (change)="range=$any($event.target).value;load()" [disabled]="loading"><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label><small>Green: healthy · Yellow: attention · Red: critical · Gray: unavailable · Blank: no reading</small>}@if(data.historyError){<p role="alert">{{data.historyError}}</p>}</div><div class="health-checks">@for(check of data.checks;track check.name){<article class="health-check"><header><strong>{{check.name}}</strong><span class="health-status" [class]="'health-status '+check.status">{{check.status==='ok'?'Healthy':check.status==='warning'?'Needs attention':check.status==='critical'?'Critical':'Unavailable'}}</span></header><p>{{check.detail}}</p>@if(data.history){<app-health-trend [name]="check.name" [history]="data.history"></app-health-trend>}</article>}</div>}<details><summary>What these checks can tell you</summary><p>Storage and memory describe this server, not a member’s computer. High usage can slow down requests or prevent uploads and backups. A green database check confirms a small read succeeded; it is not a performance test.</p><p>The backup worker checks the configured public HTTPS address. Missing or old results are shown as unavailable. Network checks never contact door controllers, PayPal or the original makerspace server.</p><p>Five-minute readings are kept for seven days. Hourly peaks and worst statuses are retained for 90 days; larger windows combine these into labeled summaries. Charts show only recorded samples, with gaps for unavailable history. Changes between samples can be missed. A restart resets application uptime.</p><p>If Cubit is unreachable, this page is also unreachable. Independent uptime alerts, disk monitoring and off-server recovery remain required before launch.</p></details></section>`})
export class SystemHealthComponent implements OnInit,OnDestroy {
 @Output() ready=new EventEmitter<void>(); data:any;range='24h';loading=false;error='';private request?:Subscription;
 constructor(private http:HttpClient){}
 ngOnInit(){this.load();}ngOnDestroy(){this.request?.unsubscribe();}
 load(){if(this.loading)return;this.loading=true;this.error='';this.request=this.http.get('/api/system-health',{params:{range:this.range}}).subscribe({next:data=>{this.data=data;this.loading=false;this.ready.emit();},error:()=>{this.loading=false;this.error='Could not reach the health service. Previous readings may be stale. Try again or ask the operator to check the server.';this.ready.emit();}});}
}
