// Generated by https://quicktype.io

export interface PaypalWebhook {
    id:               string;
    create_time:      string;
    resource_type:    string;
    event_type:       string;
    summary:          string;
    resource:         Resource;
    links:            Link[];
    event_version:    string;
    resource_version: string;
}

export interface Link {
    href:     string;
    rel:      string;
    method:   string;
    encType?: string;
}

export interface Resource {
    quantity:           string;
    subscriber:         Subscriber;
    create_time:        string;
    shipping_amount:    ShippingAmount;
    start_time:         string;
    update_time:        string;
    billing_info:       BillingInfo;
    links:              Link[];
    id:                 string;
    plan_id:            string;
    auto_renewal:       boolean;
    status:             string;
    status_update_time: string;
}

export interface BillingInfo {
    outstanding_balance:   ShippingAmount;
    cycle_executions:      CycleExecution[];
    last_payment:          LastPayment;
    next_billing_time:     string;
    final_payment_time:    string;
    failed_payments_count: number;
}

export interface CycleExecution {
    tenure_type:                    string;
    sequence:                       number;
    cycles_completed:               number;
    cycles_remaining:               number;
    current_pricing_scheme_version: number;
}

export interface LastPayment {
    amount: ShippingAmount;
    time:   string;
}

export interface ShippingAmount {
    currency_code: string;
    value:         string;
}

export interface Subscriber {
    name:             SubscriberName;
    email_address:    string;
    shipping_address: ShippingAddress;
}

export interface SubscriberName {
    given_name: string;
    surname:    string;
}

export interface ShippingAddress {
    name:    ShippingAddressName;
    address: Address;
}

export interface Address {
    address_line_1: string;
    address_line_2: string;
    admin_area_2:   string;
    admin_area_1:   string;
    postal_code:    string;
    country_code:   string;
}

export interface ShippingAddressName {
    full_name: string;
}
