const assert = require('assert/strict')
const { randomUUID } = require('crypto')
const { request } = require('./native-smoke.cjs')
require('ts-node/register')
const { AppDataSource: db } = require('../src/app')
const { Member } = require('../src/entity/member')
const { MemberPlan } = require('../src/entity/memberPlan')
const { MemberKey } = require('../src/entity/memberKey')
const { Plan } = require('../src/entity/plan')
const { Transaction } = require('../src/entity/transaction')
const { BillingChange } = require('../src/entity/billingChange')
const { StaffNote, BillingCharge, ChargeAdjustment, OperationsAudit, PaymentEvent, AutomationRun } = require('../src/entity/cubitOperations')
const { postedLedger, accessDecision } = require('../src/billing/posted-ledger')
const { csv } = require('../src/billing/reports')
const { day } = require('../src/billing/ledger')

async function main() {
  // The exact grace boundary is independent of month lengths and DST.
  const charge = { id:'c', memberPlanId:'p', planName:'Test', dueDate:'2026-01-01', amount:60 }
  const plan = { startDate:'2026-01-01' }
  assert.equal(accessDecision({},[plan],postedLedger([charge],[],[],'2026-03-02'),60).status,'Active')
  assert.equal(accessDecision({},[plan],postedLedger([charge],[],[],'2026-03-03'),60).status,'Inactive')
  assert.equal(accessDecision({accessHold:true,accessHoldReason:'Manual'},[plan],postedLedger([charge],[{amount:60,transactionDate:'2026-01-01'}],[],'2026-03-03'),60).status,'Inactive')
  assert.equal(postedLedger([charge],[],[{chargeId:'c',credit:10.55}],'2026-03-03').balance,49.45)
  assert.match(csv([[' =HYPERLINK("bad")','\t+cmd','@formula','-formula',-3,'a,"b"\nc']]), /"' =HYPERLINK/)
  for (const url of ['/api/cubit/automation','/api/cubit/reports','/api/cubit/reports/roster.csv']) assert.equal((await request(url)).status,401)
  const token=(await request('/login',{method:'POST',body:{email:'admin@example.test',password:'LocalDemoOnly!2026'}})).json().token
  const memberToken=(await request('/login',{method:'POST',body:{email:'alex@example.test',password:'LocalDemoOnly!2026'}})).json().token
  assert.equal((await request('/api/cubit/reports',{token:memberToken})).status,403)
  const get=async url=>{const r=await request(url,{token});assert.equal(r.status,200,r.text);return r.json()}
  const post=async (url,body,status=200)=>{const r=await request(url,{token,method:'POST',body});assert.equal(r.status,status,r.text);return r.json()}
  await db.initialize()
  const retiredTables=await db.query("SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='notification_draft'")
  assert.equal(retiredTables.length,0,'Obsolete notification drafts should be retired on startup')
  const memberId=randomUUID(),catalogId=randomUUID(),prefix='test-'+randomUUID(),events=[]
  const beforeRuns=new Set((await db.manager.find(AutomationRun)).map(r=>r.id))
  try {
    await db.manager.save(Member,db.manager.create(Member,{id:memberId,firstName:'Operations',lastName:'Fixture',email:prefix+'@example.test',paypalEmail:'',role:'member'}))
    await db.manager.save(Plan,db.manager.create(Plan,{id:catalogId,name:'Temporary test plan',monthlyCost:60,available:true}))
    const now=new Date(),start=day(new Date(now.getFullYear(),now.getMonth()-3,1)),today=day(now)
    const membership=await post('/plan/memberplan',{id:'New',memberId,planId:catalogId,startDate:start})
    const keyId=randomUUID(),disabledKeyId=randomUUID()
    await db.manager.save(MemberKey,[{id:keyId,memberId,serialNumber:prefix,status:'Active'},{id:disabledKeyId,memberId,serialNumber:prefix+'off',status:'Inactive'}])
    const bill=()=>get(`/api/cubit/members/${memberId}/billing`)
    const initial=await bill();assert.equal(initial.balance,240);assert.equal(initial.status,'Inactive')
    assert.equal(await db.manager.count(BillingCharge,{where:{memberId}}),4)
    await Promise.all([bill(),bill(),bill()]);assert.equal(await db.manager.count(BillingCharge,{where:{memberId}}),4)
    await db.manager.update(Plan,catalogId,{monthlyCost:99})
    assert.equal((await bill()).balance,240,'Changing the catalog must not reprice history')
    const note=await post(`/api/cubit/members/${memberId}/notes`,{text:'Test note <script>never execute</script>',author:'forged'},201)
    assert.equal(note.author,'admin@example.test')
    assert.equal((await get(`/api/cubit/members/${memberId}/notes`)).rows[0].text,note.text)
    assert.equal((await request(`/api/cubit/members/${memberId}/notes`,{token:memberToken})).status,403)
    const body={id:'New',memberId,amount:120,transactionDate:today,method:'Local test',description:'Test',requestKey:randomUUID()}
    const payments=await Promise.all([post('/transaction',body),post('/transaction',body),post('/transaction',body)])
    assert.ok(payments.every(p=>p.id===payments[0].id));assert.equal((await bill()).balance,120)
    assert.equal((await bill()).status,'Active','Payment restores within-grace eligibility')
    assert.equal((await db.manager.findOneByOrFail(MemberKey,{id:disabledKeyId})).status,'Inactive')
    await post('/transaction',{...body,amount:121},409)
    await post(`/api/cubit/members/${memberId}/operations`,{accessHold:true,reason:'Test staff access hold'})
    assert.equal((await bill()).status,'Inactive')
    await post('/transaction',{...body,requestKey:randomUUID(),amount:120})
    assert.equal((await bill()).status,'Inactive','Payment cannot remove a staff block')
    await post(`/api/cubit/members/${memberId}/operations`,{accessHold:false,reason:'Release test hold'})
    assert.equal((await bill()).status,'Active')
    const corrected=await post('/transaction',{...body,id:payments[0].id,requestKey:randomUUID(),amount:100,correctionReason:'Correct test amount'})
    assert.equal((await db.manager.findOneByOrFail(Transaction,{id:payments[0].id})).amount,'120.00')
    assert.equal((await bill()).balance,20)
    assert.equal((await db.manager.findOneByOrFail(Transaction,{id:payments[0].id})).correctedBy,corrected.id)
    await post('/transaction',{...body,id:payments[0].id,requestKey:randomUUID(),amount:90,correctionReason:'Stale edit'},409)
    const credit={credit:10.55,reason:'Test staff credit',requestKey:randomUUID()}
    await post(`/api/cubit/charges/${initial.charges[0].id}/adjustments`,credit)
    await post(`/api/cubit/charges/${initial.charges[0].id}/adjustments`,credit)
    assert.equal((await bill()).balance,9.45)
    await post(`/api/cubit/charges/${initial.charges[0].id}/adjustments`,{...credit,credit:60,requestKey:randomUUID()},400)
    const capture=prefix+'-capture'
    const simulate=async (kind,resourceId,amount,parentResourceId='')=>{
      const id=prefix+'-'+events.length;events.push(id)
      return post('/api/cubit/automation/events/simulate',{id,kind,resourceId,amount,parentResourceId,eventDate:today},201)
    }
    const event=await simulate('payment',capture,60)
    await post(`/api/cubit/automation/events/${event.id}/process`,{})
    assert.equal((await db.manager.findOneByOrFail(PaymentEvent,{id:event.id})).status,'Unmatched')
    await post(`/api/cubit/automation/events/${event.id}/process`,{memberId})
    const duplicate=await simulate('payment',capture,60)
    await post(`/api/cubit/automation/events/${duplicate.id}/process`,{memberId})
    assert.equal(await db.manager.count(Transaction,{where:{requestKey:'paypal:payment:'+capture}}),1)
    const refund=await simulate('refund',prefix+'-refund',20,capture)
    await post(`/api/cubit/automation/events/${refund.id}/process`,{memberId})
    const refundDuplicate=await simulate('refund',prefix+'-refund',20,capture)
    await post(`/api/cubit/automation/events/${refundDuplicate.id}/process`,{memberId})
    const refundRest=await simulate('refund',prefix+'-refund-rest',40,capture)
    await post(`/api/cubit/automation/events/${refundRest.id}/process`,{memberId})
    const excess=await simulate('refund',prefix+'-refund-excess',1,capture)
    await post(`/api/cubit/automation/events/${excess.id}/process`,{memberId},400)
    assert.equal((await bill()).balance,9.45,'Duplicate events and refunded capture leave balance unchanged')
    const cancel=await simulate('cancellation',prefix+'-cancel',0)
    const review=await post(`/api/cubit/automation/events/${cancel.id}/process`,{memberId})
    assert.equal(review.status,'Needs final billing date')
    assert.equal((await bill()).balance,9.45,'Cancellation must await staff date')
    const cutoff=day(new Date(now.getFullYear(),now.getMonth()-1,1))
    await post(`/api/cubit/plans/${membership.id}/cutoff`,{finalBillingDate:cutoff,reason:'Test cancellation',expectedDate:null})
    const ended=await bill();assert.equal(ended.status,'Canceled');assert.equal(ended.voidedCharges.length,1)
    assert.equal((await post(`/api/cubit/automation/events/${cancel.id}/process`,{memberId})).status,'Processed')
    // Reopening a corrected cutoff reuses original charge IDs and rates.
    await post(`/api/cubit/plans/${membership.id}/cutoff`,{finalBillingDate:today,reason:'Test corrected cutoff',expectedDate:cutoff})
    assert.equal((await bill()).balance,9.45);assert.equal(await db.manager.count(BillingCharge,{where:{memberId}}),4)
    const chargeCount=await db.manager.count(BillingCharge),runCount=await db.manager.count(AutomationRun)
    await post('/api/cubit/automation/run',{preview:true})
    assert.equal(await db.manager.count(BillingCharge),chargeCount);assert.equal(await db.manager.count(AutomationRun),runCount)
    await post('/api/cubit/automation/run',{preview:false})
    const repeat=await post('/api/cubit/automation/run',{preview:false})
    assert.equal(repeat.newCharges,0);assert.ok(!('notificationPreviews' in repeat))
    const report=await get(`/api/cubit/reports?from=${start}&to=${today}`)
    assert.ok(report.months.length===4 && report.summary.members>=76)
    assert.ok(!('aging' in report))
    assert.ok(report.months.every(m=>Number.isInteger(m.activeMembers) && m.activeMembers>=0))
    assert.equal(report.months.at(-1).activeMembers,report.summary.active)
    assert.equal(report.months.at(-1).membershipAsOf,today)
    assert.equal(report.months.at(-1).membershipEstimated,false)
    assert.equal((await request('/roadmap',{accept:'text/html'})).status,404)
    for(const type of ['roster','transactions','overdue','checkins']){
      const out=await request(`/api/cubit/reports/${type}.csv?from=${start}&to=${today}`,{token})
      assert.equal(out.status,200);assert.match(out.headers['content-type'],/text\/csv/);assert.match(out.text,/\r\n/)
    }
    assert.equal((await request('/api/cubit/reports?from=bad',{token})).status,400)
    assert.equal((await request('/paypal/webhook',{method:'POST',body:{}})).status,403)
    const automation=await get('/api/cubit/automation');assert.ok(!('notifications' in automation))
    assert.ok(!('renewalReminders' in automation.settings))
    await post('/api/cubit/automation/settings',{...automation.settings,renewalReminders:true},400)
    assert.ok(!('weeklyDigest' in automation.settings) && !('digestRecipient' in automation.settings))
    assert.ok(!('equipment' in report) && !('equipment' in report.summary))
    assert.equal((await request('/api/cubit/reports/equipment.csv',{token})).status,404)
    assert.equal((await request('/equipmentlist',{accept:'text/html'})).status,404)
    const editUrl=`/api/cubit/charges/${initial.charges[0].id}/correct`
    const edit={amount:75,expectedAmount:49.45,reason:'Correct the charge amount',requestKey:randomUUID()}
    await post(editUrl,edit);await post(editUrl,edit)
    assert.equal((await bill()).balance,35)
    await post(editUrl,{...edit,amount:80,requestKey:randomUUID()},409)
    await post(editUrl,{amount:0,expectedAmount:75,reason:'Waive the charge',requestKey:randomUUID()})
    assert.equal((await bill()).balance,-40)
    await post(editUrl,{amount:49.45,expectedAmount:0,reason:'Undo the test waiver',requestKey:randomUUID()})
    assert.equal((await bill()).balance,9.45)
    await post(editUrl,{amount:-1,expectedAmount:49.45,reason:'Invalid',requestKey:randomUUID()},400)
    const manual={amount:12.34,date:today,description:'One-time fee',requestKey:randomUUID()}
    const manualRows=await Promise.all([post(`/api/cubit/members/${memberId}/charges`,manual),post(`/api/cubit/members/${memberId}/charges`,manual)])
    assert.equal(manualRows[0].id,manualRows[1].id)
    assert.equal((await bill()).balance,21.79)
    await post(`/api/cubit/charges/${manualRows[0].id}/correct`,{amount:0,expectedAmount:12.34,reason:'Undo test fee',requestKey:randomUUID()})
    assert.equal((await bill()).balance,9.45)
    const removable=await post('/transaction',{...body,amount:3.21,requestKey:randomUUID()})
    assert.equal((await bill()).balance,6.24)
    await post('/transaction',{...body,id:removable.id,amount:0,requestKey:randomUUID(),correctionReason:'Remove a mistaken payment'})
    assert.equal((await bill()).balance,9.45)
    assert.equal(Number((await db.manager.findOneByOrFail(Transaction,{id:removable.id})).amount),3.21)
    await post('/transaction',{...body,amount:0,requestKey:randomUUID()},400)
  } finally {
    for(const e of events)await db.manager.delete(PaymentEvent,{id:e})
    for(const entity of [StaffNote,ChargeAdjustment,BillingCharge,BillingChange,OperationsAudit,Transaction,MemberKey,MemberPlan])await db.manager.delete(entity,{memberId})
    await db.manager.delete(Member,{id:memberId});await db.manager.delete(Plan,{id:catalogId})
    for(const r of await db.manager.find(AutomationRun))if(!beforeRuns.has(r.id)&&r.trigger==='admin@example.test')await db.manager.delete(AutomationRun,{id:r.id})
    await db.destroy()
  }
  console.log('PASS: posted charges, rate snapshots, atomic/idempotent payments, reversals, charge edits/waivers/restoration, one-time charges, payment removal, cutoff history, grace, staff holds, notes, event reconciliation, automation, report exports, removed features and local isolation.')
}
main().catch(e=>{console.error(e.stack);process.exitCode=1})
